### PR TITLE
Fix for Issue #16

### LINKED ISSUE #16: Type include interface field
```cs
        private class MyClass
        {
            public readonly ICollection<string> Collection = new List<string>();
        }

        [Fact]
        public void CanCopyInterfaceField()
        {
            MyClass original = new MyClass();

            original.Collection.Add("A");

            var result = DeepCopier.Copy(original);

            Assert.NotSame(original, result); //Failure
            Assert.NotSame(original.Collection, result.Collection); //Failure
        }
```
The result  is failure.

### PR DESCRIPTION
**Pull request by Tornhoof**
This fixes #16, interfaces were not checked in the immutability check.

### CODE REVIEW

**Comment by tangdf** [comment]
If the type is a an abstract class?

**Comment by Tornhoof** [comment]
Makes sense, adding a test case for abstract too.

**Comment by tangdf** [comment]
If the type is not an **sealed** class?

**Comment by Tornhoof** [comment]
Yeah, you're right, adding tests and simplyifing the checks, as being not sealed is the interesting part in the check

**Pull request merged**
